AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with public access block configuration

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create
    Default: my-automated-resume-bucket
    AllowedPattern: '^[a-z0-9.-]{3,63}$'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true