AWSTemplateFormatVersion: '2010-09-09'
Description: Create a DynamoDB Table To Store Resume Submissions and Enable Streams (Used for Lambda Processing)

Parameters:
  DynamoDBTableName:
    Type: String
    Default: submissionDB
    Description: Name of the DynamoDB Table

  DynamoDBStreamEnabled:
    Type: String
    Default: true
    Description: Enable DynamoDB Streams (true/false)

  DynamoDBStreamViewType:
    Type: String
    Default: NEW_AND_OLD_IMAGES
    Description: View type for DynamoDB Streams

  DynamoDBBillingMode:
    Type: String
    Default: PAY_PER_REQUEST
    Description: Billing mode (PROVISIONED or PAY_PER_REQUEST)

Conditions:
  IsStreamEnabled: !Equals [!Ref DynamoDBStreamEnabled, 'true']

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-${DynamoDBTableName}'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: !Ref DynamoDBBillingMode
      StreamSpecification: !If
        - IsStreamEnabled
        - StreamViewType: !Ref DynamoDBStreamViewType
        - !Ref "AWS::NoValue"

Outputs:
  DynamoDBTableName:
    Description: Name of the DynamoDB Table
    Value: !Sub '${AWS::StackName}-${DynamoDBTableName}'
    # Export:
    #   Name: !Sub '${AWS::StackName}-DynamoDBTableName'

  DynamoDBTableArn:
    Description: ARN of the DynamoDB Table
    Value: !GetAtt MyDynamoDBTable.Arn

  DynamoDBStreamArn:
    Condition: IsStreamEnabled
    Description: ARN of the DynamoDB Stream (if enabled)
    Value: !GetAtt MyDynamoDBTable.StreamArn 
    # Export:
    #   Name: !Sub '${AWS::StackName}-${DynamoDBTableName}-StreamArn'

