AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket to store resumes and related files for the Automated Resume Project

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create
    Default: my-automated-resume-bucket
    AllowedPattern: '^[a-z0-9.-]{3,63}$'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${BucketName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref MyS3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  BucketArn:
    Description: The ARN of the created S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"